package com.bot.intelligence;

import java.io.BufferedWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Properties;

/**
 * Fully autonomous, validation-gated daily entry/exit policy evolution.
 *
 * This promotes tomorrow's entry/exit behavior automatically, but only as a
 * versioned policy file and only after deterministic validation gates pass. It
 * does not rewrite live Java code during market hours. Source evolution remains
 * a separate, stricter after-hours path.
 */
public final class AutonomousEntryExitPolicyPromotionPipeline {
    private final boolean enabled = envBool("AUTONOMOUS_ENTRY_EXIT_POLICY_PROMOTION_ENABLED", true);
    private final Path activePath = Path.of(env("ENTRY_EXIT_ACTIVE_POLICY_PATH", "logs/entry_exit_policy_active.properties"));
    private final Path candidatePath = Path.of(env("ENTRY_EXIT_CANDIDATE_POLICY_PATH", "logs/entry_exit_policy_candidate.properties"));
    private final Path reportPath = Path.of(env("ENTRY_EXIT_POLICY_PROMOTION_REPORT_PATH", "logs/entry_exit_policy_promotion_report.txt"));
    private final Path tradeOutcomesPath = Path.of(env("TRADE_OUTCOMES_PATH", "logs/trade_outcomes.csv"));
    private final Path dynamicJournalPath = Path.of(env("DYNAMIC_ENTRY_EXIT_AGENT_JOURNAL", "logs/dynamic_entry_exit_agent.csv"));
    private final Path openAiReviewPath = Path.of(env("OPENAI_NIGHTLY_ENTRY_EXIT_REVIEW_PATH", "logs/openai_nightly_entry_exit_policy_review.json"));

    public Result run() {
        long started = System.currentTimeMillis();
        List<String> notes = new ArrayList<>();
        if (!enabled) {
            writeReport(false, false, "disabled", notes, null, null);
            return new Result(false, false, "disabled", System.currentTimeMillis() - started);
        }

        EntryExitAdaptivePolicy.writeDefaultIfMissing(activePath);
        PerformanceSnapshot current = PerformanceSnapshot.from(tradeOutcomesPath, dynamicJournalPath);
        Properties incumbent = load(activePath);
        Properties candidate = buildCandidate(incumbent, current, notes);
        clampCandidate(candidate, notes);
        save(candidatePath, candidate, "Candidate generated by autonomous entry/exit policy evolution.");

        ValidationResult validation = validateCandidate(incumbent, candidate, current, notes);
        boolean promoted = false;
        String message;
        if (validation.passed) {
            save(activePath, candidate, "AUTO-PROMOTED: validated autonomous entry/exit policy for next live session.");
            promoted = true;
            message = "promoted candidate to " + activePath;
        } else {
            message = "candidate rejected: " + validation.reason;
        }
        writeReport(true, promoted, message, notes, current, validation);
        return new Result(true, promoted, message, System.currentTimeMillis() - started);
    }

    private Properties buildCandidate(Properties incumbent, PerformanceSnapshot s, List<String> notes) {
        Properties p = new Properties();
        p.putAll(incumbent);
        String version = "entry-exit-" + Instant.now().toString().replace(':', '-');
        p.setProperty("policy.version", version);
        p.setProperty("policy.generatedAt", Instant.now().toString());
        p.setProperty("policy.source", "autonomous-nightly-openai-plus-statistical-validation");
        p.setProperty("policy.openai.reviewPath", openAiReviewPath.toString());

        double minScore = d(incumbent, "DYNAMIC_ENTRY_MIN_SCORE", 0.66);
        double minRvol = d(incumbent, "DYNAMIC_ENTRY_MIN_RVOL", 0.65);
        double minNotionalFraction = d(incumbent, "DYNAMIC_ENTRY_MIN_NOTIONAL_FRACTION", 0.0075);
        double minNotionalDollars = d(incumbent, "DYNAMIC_ENTRY_MIN_NOTIONAL_DOLLARS", 600.0);
        double hardLoss = d(incumbent, "DYNAMIC_EXIT_HARD_LOSS_PERCENT", -2.25);
        long minJudge = l(incumbent, "DYNAMIC_EXIT_MIN_JUDGEMENT_SECONDS", 360L);
        long noFollow = l(incumbent, "DYNAMIC_EXIT_NO_FOLLOW_THROUGH_SECONDS", 1500L);
        int maxLosses = i(incumbent, "DYNAMIC_ENTRY_MAX_RECENT_STRATEGY_LOSSES", 3);
        long cooldown = l(incumbent, "DYNAMIC_ENTRY_TICKER_COOLDOWN_SECONDS", 2400L);

        if (s.trades == 0) {
            notes.add("No trade outcomes found; preserving incumbent with conservative bootstrap defaults.");
            minScore = Math.max(minScore, 0.66);
            minRvol = Math.max(minRvol, 0.65);
        } else if (s.expectancy < 0.0 || s.winRate < 0.42 || s.tinyTradeRate > 0.35 || s.avgHoldMinutes < 10.0) {
            notes.add("Loss/churn detected; tightening entry gates and extending judgement/cooldowns.");
            minScore += s.expectancy < 0 ? 0.025 : 0.010;
            minRvol += s.tinyTradeRate > 0.35 ? 0.15 : 0.05;
            minNotionalFraction += 0.0025;
            minNotionalDollars += 250.0;
            hardLoss = Math.max(hardLoss, -2.00); // less negative = tighter max loss
            minJudge += 120L;
            noFollow += 180L;
            maxLosses = Math.max(2, maxLosses - 1);
            cooldown += 600L;
        } else if (s.expectancy > 0.004 && s.winRate > 0.52 && s.maxDrawdown > -0.03) {
            notes.add("Incumbent behavior appears profitable/stable; allowing slight flexibility.");
            minScore -= 0.010;
            minRvol -= 0.05;
            minJudge = Math.max(240L, minJudge - 60L);
        } else {
            notes.add("Mixed performance; using small conservative adjustment.");
            minScore += 0.010;
            minRvol += 0.05;
        }

        if (readTail(openAiReviewPath, 4000).toLowerCase(Locale.ROOT).contains("overtrading")) {
            notes.add("OpenAI review flagged overtrading; applying additional anti-churn tightening.");
            minScore += 0.010;
            cooldown += 300L;
            noFollow += 120L;
        }

        // Keep the nightly learner autonomous, but prevent it from self-tightening the live buy path
        // into another no-trade day. The live OpenAI governor and hard risk layer can still veto poor
        // setups; these caps ensure candidates reach the governor for reasoning.
        minScore = Math.max(0.58, Math.min(minScore, d(incumbent, "DYNAMIC_ENTRY_POLICY_MAX_MIN_SCORE", 0.72)));
        minRvol = Math.max(0.35, Math.min(minRvol, d(incumbent, "DYNAMIC_ENTRY_POLICY_MAX_MIN_RVOL", 0.60)));
        minNotionalFraction = Math.max(0.0035, Math.min(minNotionalFraction, d(incumbent, "DYNAMIC_ENTRY_POLICY_MAX_MIN_NOTIONAL_FRACTION", 0.012)));
        minNotionalDollars = Math.max(350.0, Math.min(minNotionalDollars, d(incumbent, "DYNAMIC_ENTRY_POLICY_MAX_MIN_NOTIONAL_DOLLARS", 1200.0)));

        p.setProperty("DYNAMIC_ENTRY_MIN_SCORE", f(minScore));
        p.setProperty("DYNAMIC_ENTRY_A_PLUS_SCORE", f(Math.max(Math.min(d(incumbent, "DYNAMIC_ENTRY_A_PLUS_SCORE", 0.84), 0.86), minScore + 0.08)));
        p.setProperty("DYNAMIC_ENTRY_MIN_RVOL", f(minRvol));
        p.setProperty("DYNAMIC_ENTRY_MIN_NOTIONAL_FRACTION", f(minNotionalFraction));
        p.setProperty("DYNAMIC_ENTRY_MIN_NOTIONAL_DOLLARS", f(minNotionalDollars));
        p.setProperty("DYNAMIC_ENTRY_MAX_LONG_FRACTION", f(d(incumbent, "DYNAMIC_ENTRY_MAX_LONG_FRACTION", 0.050)));
        p.setProperty("DYNAMIC_ENTRY_MAX_SHORT_FRACTION", f(d(incumbent, "DYNAMIC_ENTRY_MAX_SHORT_FRACTION", 0.035)));
        p.setProperty("DYNAMIC_ENTRY_MAX_RECENT_STRATEGY_LOSSES", Integer.toString(maxLosses));
        p.setProperty("DYNAMIC_ENTRY_TICKER_COOLDOWN_SECONDS", Long.toString(cooldown));
        p.setProperty("DYNAMIC_ENTRY_STRATEGY_LOSS_WINDOW_MINUTES", Long.toString(l(incumbent, "DYNAMIC_ENTRY_STRATEGY_LOSS_WINDOW_MINUTES", 240L)));
        p.setProperty("DYNAMIC_EXIT_HARD_LOSS_PERCENT", f(hardLoss));
        p.setProperty("DYNAMIC_EXIT_MIN_JUDGEMENT_SECONDS", Long.toString(minJudge));
        p.setProperty("DYNAMIC_EXIT_WEAK_ENTRY_CONFIDENCE", f(Math.max(d(incumbent, "DYNAMIC_EXIT_WEAK_ENTRY_CONFIDENCE", 0.82), 0.82)));
        p.setProperty("DYNAMIC_EXIT_WEAK_ENTRY_PRIORITY", f(Math.max(d(incumbent, "DYNAMIC_EXIT_WEAK_ENTRY_PRIORITY", 0.060), 0.060)));
        p.setProperty("DYNAMIC_EXIT_WEAK_DECAY_LOSS_PERCENT", f(Math.min(d(incumbent, "DYNAMIC_EXIT_WEAK_DECAY_LOSS_PERCENT", -0.65), -0.55)));
        p.setProperty("DYNAMIC_EXIT_PROFIT_GIVEBACK_PERCENT", f(d(incumbent, "DYNAMIC_EXIT_PROFIT_GIVEBACK_PERCENT", 0.70)));
        p.setProperty("DYNAMIC_EXIT_MIN_BEST_GAIN_PERCENT", f(d(incumbent, "DYNAMIC_EXIT_MIN_BEST_GAIN_PERCENT", 1.00)));
        p.setProperty("DYNAMIC_EXIT_NO_FOLLOW_THROUGH_SECONDS", Long.toString(noFollow));
        p.setProperty("DYNAMIC_EXIT_NO_FOLLOW_BEST_GAIN_PERCENT", f(d(incumbent, "DYNAMIC_EXIT_NO_FOLLOW_BEST_GAIN_PERCENT", 0.55)));

        p.setProperty("validation.baseline.trades", Integer.toString(s.trades));
        p.setProperty("validation.baseline.expectancy", f(s.expectancy));
        p.setProperty("validation.baseline.winRate", f(s.winRate));
        p.setProperty("validation.baseline.tinyTradeRate", f(s.tinyTradeRate));
        p.setProperty("validation.baseline.avgHoldMinutes", f(s.avgHoldMinutes));
        return p;
    }

    private void clampCandidate(Properties p, List<String> notes) {
        setD(p, "DYNAMIC_ENTRY_MIN_SCORE", clamp(d(p, "DYNAMIC_ENTRY_MIN_SCORE", 0.66), 0.62, 0.94));
        setD(p, "DYNAMIC_ENTRY_A_PLUS_SCORE", clamp(d(p, "DYNAMIC_ENTRY_A_PLUS_SCORE", 0.84), d(p, "DYNAMIC_ENTRY_MIN_SCORE", 0.66) + 0.04, 0.98));
        setD(p, "DYNAMIC_ENTRY_MIN_RVOL", clamp(d(p, "DYNAMIC_ENTRY_MIN_RVOL", 0.65), 0.50, 2.50));
        setD(p, "DYNAMIC_ENTRY_MIN_NOTIONAL_FRACTION", clamp(d(p, "DYNAMIC_ENTRY_MIN_NOTIONAL_FRACTION", 0.0075), 0.004, 0.035));
        setD(p, "DYNAMIC_ENTRY_MIN_NOTIONAL_DOLLARS", clamp(d(p, "DYNAMIC_ENTRY_MIN_NOTIONAL_DOLLARS", 600), 400, 3500));
        setD(p, "DYNAMIC_ENTRY_MAX_LONG_FRACTION", clamp(d(p, "DYNAMIC_ENTRY_MAX_LONG_FRACTION", 0.05), 0.015, 0.08));
        setD(p, "DYNAMIC_ENTRY_MAX_SHORT_FRACTION", clamp(d(p, "DYNAMIC_ENTRY_MAX_SHORT_FRACTION", 0.035), 0.010, 0.06));
        setD(p, "DYNAMIC_EXIT_HARD_LOSS_PERCENT", clamp(d(p, "DYNAMIC_EXIT_HARD_LOSS_PERCENT", -2.25), -4.0, -1.0));
        setL(p, "DYNAMIC_EXIT_MIN_JUDGEMENT_SECONDS", clampL(l(p, "DYNAMIC_EXIT_MIN_JUDGEMENT_SECONDS", 360), 180, 1200));
        setL(p, "DYNAMIC_EXIT_NO_FOLLOW_THROUGH_SECONDS", clampL(l(p, "DYNAMIC_EXIT_NO_FOLLOW_THROUGH_SECONDS", 1500), 600, 3600));
        setL(p, "DYNAMIC_ENTRY_TICKER_COOLDOWN_SECONDS", clampL(l(p, "DYNAMIC_ENTRY_TICKER_COOLDOWN_SECONDS", 2400), 600, 7200));
        int losses = Math.max(1, Math.min(6, i(p, "DYNAMIC_ENTRY_MAX_RECENT_STRATEGY_LOSSES", 3)));
        p.setProperty("DYNAMIC_ENTRY_MAX_RECENT_STRATEGY_LOSSES", Integer.toString(losses));
        notes.add("Candidate clamped inside immutable operational bounds.");
    }

    private ValidationResult validateCandidate(Properties incumbent, Properties candidate, PerformanceSnapshot s, List<String> notes) {
        double minScore = d(candidate, "DYNAMIC_ENTRY_MIN_SCORE", 0.66);
        double minNotional = d(candidate, "DYNAMIC_ENTRY_MIN_NOTIONAL_DOLLARS", 1000.0);
        double maxLong = d(candidate, "DYNAMIC_ENTRY_MAX_LONG_FRACTION", 0.05);
        double maxShort = d(candidate, "DYNAMIC_ENTRY_MAX_SHORT_FRACTION", 0.035);
        double hardLoss = d(candidate, "DYNAMIC_EXIT_HARD_LOSS_PERCENT", -2.25);
        if (minScore < 0.62) return ValidationResult.fail("entry score below safety floor");
        if (minNotional < 500) return ValidationResult.fail("minimum notional too small; would allow penny-drip churn");
        if (maxLong > 0.08 || maxShort > 0.06) return ValidationResult.fail("position fraction too aggressive");
        if (hardLoss < -4.0 || hardLoss > -1.0) return ValidationResult.fail("hard-loss percent outside safe bounds");

        double oldScore = d(incumbent, "DYNAMIC_ENTRY_MIN_SCORE", 0.66);
        boolean materiallyDifferent = Math.abs(minScore - oldScore) >= 0.004
                || Math.abs(d(candidate, "DYNAMIC_ENTRY_MIN_RVOL", 0.65) - d(incumbent, "DYNAMIC_ENTRY_MIN_RVOL", 0.65)) >= 0.02
                || Math.abs(l(candidate, "DYNAMIC_EXIT_MIN_JUDGEMENT_SECONDS", 360) - l(incumbent, "DYNAMIC_EXIT_MIN_JUDGEMENT_SECONDS", 360)) >= 30;
        if (!materiallyDifferent && s.trades > 0) return ValidationResult.fail("candidate not materially different from incumbent");

        double estimatedChurnReduction = estimateChurnReduction(incumbent, candidate, s);
        double estimatedExpectancyLift = estimateExpectancyLift(incumbent, candidate, s);
        notes.add("Estimated churn reduction=" + f(estimatedChurnReduction) + " expectancyLift=" + f(estimatedExpectancyLift));

        if (s.trades >= 8 && s.expectancy < 0.0 && estimatedChurnReduction < 0.05 && estimatedExpectancyLift < 0.001) {
            return ValidationResult.fail("candidate does not sufficiently address negative expectancy/churn");
        }
        if (s.trades >= 8 && s.tinyTradeRate > 0.35 && estimatedChurnReduction < 0.08) {
            return ValidationResult.fail("candidate does not sufficiently reduce tiny-trade churn");
        }
        return ValidationResult.pass("validation passed; candidate improves expected churn/expectancy while preserving risk guardrails");
    }

    private double estimateChurnReduction(Properties oldP, Properties newP, PerformanceSnapshot s) {
        double scoreLift = d(newP, "DYNAMIC_ENTRY_MIN_SCORE", 0.66) - d(oldP, "DYNAMIC_ENTRY_MIN_SCORE", 0.66);
        double notionalLift = d(newP, "DYNAMIC_ENTRY_MIN_NOTIONAL_DOLLARS", 1000) - d(oldP, "DYNAMIC_ENTRY_MIN_NOTIONAL_DOLLARS", 1000);
        double cooldownLift = l(newP, "DYNAMIC_ENTRY_TICKER_COOLDOWN_SECONDS", 2400) - l(oldP, "DYNAMIC_ENTRY_TICKER_COOLDOWN_SECONDS", 2400);
        return clamp(scoreLift * 4.0 + notionalLift / 5000.0 + cooldownLift / 12000.0 + Math.max(0, s.tinyTradeRate - 0.25) * 0.25, 0, 0.60);
    }

    private double estimateExpectancyLift(Properties oldP, Properties newP, PerformanceSnapshot s) {
        double churnReduction = estimateChurnReduction(oldP, newP, s);
        double lossPressure = Math.max(0, -s.expectancy) + Math.max(0, 0.45 - s.winRate) * 0.01;
        return churnReduction * (0.0025 + lossPressure);
    }

    private void writeReport(boolean attempted, boolean promoted, String message, List<String> notes, PerformanceSnapshot snapshot, ValidationResult validation) {
        StringBuilder b = new StringBuilder();
        b.append("AUTONOMOUS ENTRY/EXIT POLICY PROMOTION REPORT\n");
        b.append("timestamp=").append(Instant.now()).append('\n');
        b.append("attempted=").append(attempted).append('\n');
        b.append("promoted=").append(promoted).append('\n');
        b.append("message=").append(message).append('\n');
        b.append("activePolicy=").append(activePath).append('\n');
        b.append("candidatePolicy=").append(candidatePath).append('\n');
        if (snapshot != null) b.append("performance=").append(snapshot).append('\n');
        if (validation != null) b.append("validation=").append(validation.reason).append(" passed=").append(validation.passed).append('\n');
        b.append("notes=\n");
        if (notes.isEmpty()) b.append("- none\n");
        for (String n : notes) b.append("- ").append(n).append('\n');
        try {
            Path parent = reportPath.getParent(); if (parent != null) Files.createDirectories(parent);
            Files.writeString(reportPath, b.toString(), StandardCharsets.UTF_8);
        } catch (Exception e) {
            System.out.println("ENTRY/EXIT POLICY PROMOTION REPORT WRITE FAILED: " + e.getMessage());
        }
    }

    private static PerformanceSnapshot loadTradePerformance(Path outcomes, Path dynamicJournal) {
        return PerformanceSnapshot.from(outcomes, dynamicJournal);
    }

    private static Properties load(Path path) {
        Properties p = new Properties();
        try { if (Files.exists(path)) try (var in = Files.newInputStream(path)) { p.load(in); } } catch (Exception ignored) {}
        return p;
    }

    private static void save(Path path, Properties p, String comment) {
        try {
            Path parent = path.getParent(); if (parent != null) Files.createDirectories(parent);
            try (var out = Files.newOutputStream(path)) { p.store(out, comment); }
        } catch (Exception e) {
            throw new RuntimeException("Failed to write policy " + path + ": " + e.getMessage(), e);
        }
    }

    private static String readTail(Path path, int chars) {
        try {
            if (!Files.exists(path)) return "";
            String text = Files.readString(path, StandardCharsets.UTF_8);
            return text.length() <= chars ? text : text.substring(text.length() - chars);
        } catch (Exception e) { return ""; }
    }

    private static double d(Properties p, String k, double f) { try { return Double.parseDouble(p.getProperty(k, Double.toString(f)).trim()); } catch (Exception e) { return f; } }
    private static int i(Properties p, String k, int f) { try { return Integer.parseInt(p.getProperty(k, Integer.toString(f)).trim()); } catch (Exception e) { return f; } }
    private static long l(Properties p, String k, long f) { try { return Long.parseLong(p.getProperty(k, Long.toString(f)).trim()); } catch (Exception e) { return f; } }
    private static void setD(Properties p, String k, double v) { p.setProperty(k, f(v)); }
    private static void setL(Properties p, String k, long v) { p.setProperty(k, Long.toString(v)); }
    private static double clamp(double v, double lo, double hi) { return Math.max(lo, Math.min(hi, v)); }
    private static long clampL(long v, long lo, long hi) { return Math.max(lo, Math.min(hi, v)); }
    private static String f(double v) { return String.format(Locale.US, "%.6f", v); }
    private static String env(String k, String f) { String v = System.getenv(k); return v == null || v.isBlank() ? f : v.trim(); }
    private static boolean envBool(String k, boolean f) { String v = System.getenv(k); if (v == null || v.isBlank()) return f; String x = v.trim().toLowerCase(Locale.ROOT); return x.equals("true") || x.equals("1") || x.equals("yes") || x.equals("on"); }

    public static final class Result {
        public final boolean attempted; public final boolean promoted; public final String message; public final long elapsedMs;
        Result(boolean attempted, boolean promoted, String message, long elapsedMs) { this.attempted = attempted; this.promoted = promoted; this.message = message; this.elapsedMs = elapsedMs; }
        public String summary() { return "attempted=" + attempted + " promoted=" + promoted + " elapsedMs=" + elapsedMs + " " + message; }
    }

    private static final class ValidationResult {
        final boolean passed; final String reason;
        private ValidationResult(boolean passed, String reason) { this.passed = passed; this.reason = reason; }
        static ValidationResult pass(String r) { return new ValidationResult(true, r); }
        static ValidationResult fail(String r) { return new ValidationResult(false, r); }
    }

    private static final class PerformanceSnapshot {
        final int trades; final double expectancy; final double winRate; final double tinyTradeRate; final double avgHoldMinutes; final double maxDrawdown;
        PerformanceSnapshot(int trades, double expectancy, double winRate, double tinyTradeRate, double avgHoldMinutes, double maxDrawdown) {
            this.trades = trades; this.expectancy = expectancy; this.winRate = winRate; this.tinyTradeRate = tinyTradeRate; this.avgHoldMinutes = avgHoldMinutes; this.maxDrawdown = maxDrawdown;
        }
        static PerformanceSnapshot from(Path outcomes, Path dynamicJournal) {
            List<Double> returns = new ArrayList<>();
            List<Double> notionals = new ArrayList<>();
            List<Double> holds = new ArrayList<>();
            parseReturns(outcomes, returns, notionals, holds);
            if (returns.isEmpty()) parseDynamicJournal(dynamicJournal, returns, notionals, holds);
            int n = returns.size();
            if (n == 0) return new PerformanceSnapshot(0, 0, 0, 0, 0, 0);
            double sum = 0, wins = 0, tiny = 0, hold = 0, equity = 0, peak = 0, maxDd = 0;
            for (int idx = 0; idx < n; idx++) {
                double r = returns.get(idx);
                sum += r;
                if (r > 0) wins++;
                if (idx < notionals.size() && notionals.get(idx) > 0 && notionals.get(idx) < 750) tiny++;
                if (idx < holds.size()) hold += Math.max(0, holds.get(idx));
                equity += r;
                peak = Math.max(peak, equity);
                maxDd = Math.min(maxDd, equity - peak);
            }
            return new PerformanceSnapshot(n, sum / n, wins / n, tiny / n, hold / Math.max(1, n), maxDd);
        }
        private static void parseReturns(Path path, List<Double> returns, List<Double> notionals, List<Double> holds) {
            try {
                if (!Files.exists(path)) return;
                List<String> lines = Files.readAllLines(path, StandardCharsets.UTF_8);
                for (String line : lines.subList(Math.max(0, lines.size() - 500), lines.size())) {
                    String[] parts = line.split(",");
                    double bestReturn = Double.NaN, notional = Double.NaN, holdMin = Double.NaN;
                    for (String part : parts) {
                        String x = part.trim().toLowerCase(Locale.ROOT);
                        if (x.contains("return") || x.contains("pnl") || x.contains("gain")) bestReturn = parseEmbeddedDouble(x, bestReturn);
                        if (x.contains("notional") || x.contains("dollars")) notional = parseEmbeddedDouble(x, notional);
                        if (x.contains("hold") || x.contains("agemin")) holdMin = parseEmbeddedDouble(x, holdMin);
                    }
                    if (Double.isNaN(bestReturn)) {
                        for (String part : parts) {
                            double v = parseDoubleOrNaN(part);
                            if (!Double.isNaN(v) && Math.abs(v) < 1.0) { bestReturn = v; break; }
                        }
                    }
                    if (!Double.isNaN(bestReturn)) returns.add(bestReturn);
                    if (!Double.isNaN(notional)) notionals.add(notional);
                    if (!Double.isNaN(holdMin)) holds.add(holdMin);
                }
            } catch (Exception ignored) {}
        }
        private static void parseDynamicJournal(Path path, List<Double> returns, List<Double> notionals, List<Double> holds) {
            try {
                if (!Files.exists(path)) return;
                List<String> lines = Files.readAllLines(path, StandardCharsets.UTF_8);
                for (String line : lines.subList(Math.max(0, lines.size() - 500), lines.size())) {
                    String x = line.toLowerCase(Locale.ROOT);
                    double pnl = parseAfter(x, "pnl=");
                    if (!Double.isNaN(pnl)) returns.add(pnl / 100.0);
                    double notional = parseAfter(x, "notional=");
                    if (!Double.isNaN(notional)) notionals.add(notional);
                    double age = parseAfter(x, "agemin=");
                    if (!Double.isNaN(age)) holds.add(age);
                }
            } catch (Exception ignored) {}
        }
        private static double parseAfter(String x, String key) {
            int i = x.indexOf(key); if (i < 0) return Double.NaN;
            int s = i + key.length(); int e = s;
            while (e < x.length() && "-+.0123456789".indexOf(x.charAt(e)) >= 0) e++;
            return parseDoubleOrNaN(x.substring(s, e));
        }
        private static double parseEmbeddedDouble(String x, double fallback) {
            String cleaned = x.replaceAll("[^0-9eE+\\-.]", " ");
            for (String token : cleaned.trim().split("\\s+")) {
                double v = parseDoubleOrNaN(token);
                if (!Double.isNaN(v)) return v;
            }
            return fallback;
        }
        private static double parseDoubleOrNaN(String s) { try { return Double.parseDouble(s.trim()); } catch (Exception e) { return Double.NaN; } }
        @Override public String toString() { return "trades=" + trades + " expectancy=" + f(expectancy) + " winRate=" + f(winRate) + " tinyTradeRate=" + f(tinyTradeRate) + " avgHoldMinutes=" + f(avgHoldMinutes) + " maxDrawdown=" + f(maxDrawdown); }
    }
}
