package com.bot.intelligence;

import java.io.BufferedWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Locale;
import java.util.Properties;

/**
 * Runtime entry/exit policy loaded by the live DynamicEntryExitDecisionAgent.
 *
 * This is the fast daily adaptation surface.  The Java engine stays stable;
 * after-hours evolution promotes a validated properties file here, and the
 * next live session automatically consumes it without human intervention.
 */
public final class EntryExitAdaptivePolicy {
    private static final EntryExitAdaptivePolicy INSTANCE = new EntryExitAdaptivePolicy();

    private final Path activePath = Path.of(env("ENTRY_EXIT_ACTIVE_POLICY_PATH", "logs/entry_exit_policy_active.properties"));
    private final Properties properties = new Properties();
    private volatile long lastLoadedMs = -1L;
    private volatile boolean loaded;

    private EntryExitAdaptivePolicy() {
        reload();
    }

    public static EntryExitAdaptivePolicy getInstance() {
        return INSTANCE;
    }

    public synchronized void reload() {
        properties.clear();
        loaded = false;
        try {
            if (Files.exists(activePath)) {
                try (var in = Files.newInputStream(activePath)) {
                    properties.load(in);
                }
                loaded = true;
                lastLoadedMs = System.currentTimeMillis();
                System.out.println("ENTRY/EXIT ADAPTIVE POLICY LOADED: path=" + activePath + " keys=" + properties.size() + " version=" + get("policy.version", "unknown"));
            } else {
                lastLoadedMs = System.currentTimeMillis();
                System.out.println("ENTRY/EXIT ADAPTIVE POLICY: no active policy yet, using env/defaults. path=" + activePath);
            }
        } catch (Exception e) {
            loaded = false;
            lastLoadedMs = System.currentTimeMillis();
            System.out.println("ENTRY/EXIT ADAPTIVE POLICY LOAD FAILED: " + e.getMessage());
        }
    }

    public boolean loaded() { return loaded; }
    public long lastLoadedMs() { return lastLoadedMs; }
    public Path activePath() { return activePath; }

    public String get(String key, String fallback) {
        String envValue = System.getenv(key);
        if (envValue != null && !envValue.isBlank()) return envValue.trim();
        String policyValue = properties.getProperty(key);
        return policyValue == null || policyValue.isBlank() ? fallback : policyValue.trim();
    }

    public double getDouble(String key, double fallback) {
        try { return Double.parseDouble(get(key, Double.toString(fallback))); } catch (Exception e) { return fallback; }
    }

    public int getInt(String key, int fallback) {
        try { return Integer.parseInt(get(key, Integer.toString(fallback))); } catch (Exception e) { return fallback; }
    }

    public long getLong(String key, long fallback) {
        try { return Long.parseLong(get(key, Long.toString(fallback))); } catch (Exception e) { return fallback; }
    }

    public static void writeDefaultIfMissing(Path path) {
        try {
            if (Files.exists(path)) return;
            Path parent = path.getParent();
            if (parent != null) Files.createDirectories(parent);
            try (BufferedWriter w = Files.newBufferedWriter(path, StandardCharsets.UTF_8)) {
                w.write("# Active entry/exit policy generated by autonomous nightly validation.\n");
                w.write("policy.version=bootstrap-" + Instant.now().toString().replace(':','-') + "\n");
                w.write("policy.promotedAt=" + Instant.now() + "\n");
                w.write("policy.source=bootstrap-default\n");
                w.write("DYNAMIC_ENTRY_MIN_SCORE=0.66\n");
                w.write("DYNAMIC_ENTRY_A_PLUS_SCORE=0.84\n");
                w.write("DYNAMIC_ENTRY_MIN_NOTIONAL_FRACTION=0.0075\n");
                w.write("DYNAMIC_ENTRY_MIN_NOTIONAL_DOLLARS=600\n");
                w.write("DYNAMIC_ENTRY_MAX_LONG_FRACTION=0.060\n");
                w.write("DYNAMIC_ENTRY_MAX_SHORT_FRACTION=0.045\n");
                w.write("DYNAMIC_ENTRY_MAX_RECENT_STRATEGY_LOSSES=5\n");
                w.write("DYNAMIC_ENTRY_TICKER_COOLDOWN_SECONDS=900\n");
                w.write("DYNAMIC_ENTRY_STRATEGY_LOSS_WINDOW_MINUTES=240\n");
                w.write("DYNAMIC_ENTRY_MIN_RVOL=0.65\n");
                w.write("DYNAMIC_EXIT_HARD_LOSS_PERCENT=-2.25\n");
                w.write("DYNAMIC_EXIT_MIN_JUDGEMENT_SECONDS=240\n");
                w.write("DYNAMIC_EXIT_WEAK_ENTRY_CONFIDENCE=0.82\n");
                w.write("DYNAMIC_EXIT_WEAK_ENTRY_PRIORITY=0.060\n");
                w.write("DYNAMIC_EXIT_WEAK_DECAY_LOSS_PERCENT=-0.65\n");
                w.write("DYNAMIC_EXIT_PROFIT_GIVEBACK_PERCENT=0.70\n");
                w.write("DYNAMIC_EXIT_MIN_BEST_GAIN_PERCENT=1.00\n");
                w.write("DYNAMIC_EXIT_NO_FOLLOW_THROUGH_SECONDS=1200\n");
                w.write("DYNAMIC_EXIT_NO_FOLLOW_BEST_GAIN_PERCENT=0.55\n");
            }
        } catch (Exception e) {
            System.out.println("ENTRY/EXIT DEFAULT POLICY WRITE FAILED: " + e.getMessage());
        }
    }

    private static String env(String key, String fallback) {
        String v = System.getenv(key);
        return v == null || v.isBlank() ? fallback : v.trim();
    }
}
