package com.bot.intelligence;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.text.DecimalFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Properties;
import java.util.Set;

/**
 * Converts realized trade outcomes and offline replay rankings into a small
 * strategy policy file. Real closed-trade PnL is authoritative; replay evidence
 * is advisory and only nudges strategies that have enough samples.
 */
public final class ReplayDrivenStrategyOptimizer {

    private final Path outcomesPath;
    private final Path replayPath;
    private final Path policyPath;
    private final Path reportPath;
    private final int minOutcomeSamples;
    private final int minDisableSamples;
    private final int minReplaySamples;

    public ReplayDrivenStrategyOptimizer() {
        this(
                Path.of(env("TRADE_OUTCOME_JOURNAL_PATH", "logs/trade_outcomes.csv")),
                Path.of(env("HISTORICAL_REPLAY_REPORT_PATH", "logs/historical_replay_report.csv")),
                Path.of(env("REPLAY_STRATEGY_POLICY_PATH", "logs/replay_strategy_policy.properties")),
                Path.of(env("REPLAY_STRATEGY_REPORT_PATH", "logs/replay_strategy_report.txt")),
                envInt("REPLAY_STRATEGY_MIN_OUTCOME_SAMPLES", 8),
                envInt("REPLAY_STRATEGY_MIN_DISABLE_SAMPLES", 18),
                envInt("REPLAY_STRATEGY_MIN_REPLAY_SAMPLES", 20)
        );
    }

    ReplayDrivenStrategyOptimizer(
            Path outcomesPath,
            Path replayPath,
            Path policyPath,
            Path reportPath,
            int minOutcomeSamples,
            int minDisableSamples,
            int minReplaySamples
    ) {
        this.outcomesPath = outcomesPath;
        this.replayPath = replayPath;
        this.policyPath = policyPath;
        this.reportPath = reportPath;
        this.minOutcomeSamples = Math.max(3, minOutcomeSamples);
        this.minDisableSamples = Math.max(this.minOutcomeSamples, minDisableSamples);
        this.minReplaySamples = Math.max(5, minReplaySamples);
    }

    public Result runOnce() {
        Map<String, OutcomeStats> outcomes = readOutcomes();
        Map<String, ReplayStats> replay = readReplay();
        Set<String> strategies = new LinkedHashSet<>();
        strategies.addAll(outcomes.keySet());
        strategies.addAll(replay.keySet());

        Properties policy = new Properties();
        policy.setProperty("updatedAt", Instant.now().toString());
        policy.setProperty("description", "Generated by ReplayDrivenStrategyOptimizer. Real trade outcomes dominate; replay rankings are advisory.");
        policy.setProperty("outcomesPath", outcomesPath.toString());
        policy.setProperty("replayPath", replayPath.toString());

        List<StrategyPolicy> recommendations = new ArrayList<>();
        for (String strategy : strategies) {
            OutcomeStats o = outcomes.get(strategy);
            ReplayStats r = replay.get(strategy);
            StrategyPolicy recommendation = recommend(strategy, o, r);
            recommendations.add(recommendation);
            String prefix = "strategy." + strategy + ".";
            policy.setProperty(prefix + "outcomeSamples", Integer.toString(o == null ? 0 : o.closed));
            policy.setProperty(prefix + "realizedPnl", fmt(o == null ? 0.0 : o.totalPnl));
            policy.setProperty(prefix + "expectancy", fmt(o == null ? 0.0 : o.expectancy()));
            policy.setProperty(prefix + "winRate", fmt(o == null ? 0.0 : o.winRate()));
            policy.setProperty(prefix + "profitFactor", fmt(o == null ? 0.0 : o.profitFactor()));
            policy.setProperty(prefix + "replaySamples", Integer.toString(r == null ? 0 : r.samples));
            policy.setProperty(prefix + "avgReplayExpectedValue", fmt(r == null ? 0.0 : r.avgExpectedValue()));
            policy.setProperty(prefix + "avgReplayQuality", fmt(r == null ? 0.0 : r.avgQuality()));
            policy.setProperty(prefix + "avgReplayTargetProbability", fmt(r == null ? 0.0 : r.avgTargetProbability()));
            policy.setProperty(prefix + "decision", recommendation.decision);
            policy.setProperty(prefix + "reason", recommendation.reason);
            policy.setProperty("strategyMultiplier." + strategy, fmt(recommendation.multiplier));
            if (recommendation.disabled) {
                policy.setProperty("disabledStrategy." + strategy, "true");
            }
        }

        writePolicy(policy);
        writeReport(recommendations, outcomes, replay);
        return new Result(outcomes.size(), replay.size(), recommendations.size(), policyPath);
    }

    private StrategyPolicy recommend(String strategy, OutcomeStats outcome, ReplayStats replay) {
        double multiplier = 1.0;
        boolean disabled = false;
        StringBuilder reason = new StringBuilder();

        if (outcome != null && outcome.closed >= minOutcomeSamples) {
            double expectancy = outcome.expectancy();
            double winRate = outcome.winRate();
            double profitFactor = outcome.profitFactor();
            if (expectancy < 0.0 || profitFactor < envDouble("REPLAY_STRATEGY_MIN_PROFIT_FACTOR", 0.95)) {
                multiplier -= 0.18;
                reason.append("negative_or_weak_realized_edge ");
            }
            if (winRate < envDouble("REPLAY_STRATEGY_WEAK_WIN_RATE", 0.42)) {
                multiplier -= 0.12;
                reason.append("low_win_rate ");
            }
            if (outcome.lossStreak >= envInt("REPLAY_STRATEGY_LOSS_STREAK_PENALTY", 4)) {
                multiplier -= 0.10;
                reason.append("loss_streak ");
            }
            if (expectancy > envDouble("REPLAY_STRATEGY_STRONG_EXPECTANCY", 0.75)
                    && profitFactor >= envDouble("REPLAY_STRATEGY_STRONG_PROFIT_FACTOR", 1.35)
                    && winRate >= envDouble("REPLAY_STRATEGY_STRONG_WIN_RATE", 0.54)) {
                multiplier += 0.12;
                reason.append("strong_realized_edge ");
            }
            if (outcome.closed >= minDisableSamples
                    && outcome.totalPnl < -Math.abs(envDouble("REPLAY_STRATEGY_DISABLE_LOSS_DOLLARS", 5.0))
                    && expectancy < -Math.abs(envDouble("REPLAY_STRATEGY_DISABLE_EXPECTANCY", 0.20))
                    && profitFactor < envDouble("REPLAY_STRATEGY_DISABLE_PROFIT_FACTOR", 0.75)
                    && winRate < envDouble("REPLAY_STRATEGY_DISABLE_WIN_RATE", 0.38)) {
                disabled = allowDisable(strategy);
                multiplier = Math.min(multiplier, 0.50);
                reason.append(disabled ? "disabled_for_realized_negative_expectancy " : "severe_underperformance_size_only ");
            }
        } else {
            reason.append("insufficient_realized_samples ");
        }

        if (replay != null && replay.samples >= minReplaySamples) {
            double replayScore = replayReplayScore(replay);
            multiplier += (replayScore - 0.50) * envDouble("REPLAY_STRATEGY_REPLAY_WEIGHT", 0.25);
            reason.append("replayScore=").append(fmt(replayScore)).append(' ');
        }

        multiplier = clamp(multiplier, 0.50, 1.35);
        if (disabled) {
            multiplier = Math.min(multiplier, 0.50);
        }
        String decision = disabled ? "DISABLE" : multiplier < 0.80 ? "SHRINK" : multiplier > 1.08 ? "EXPAND" : "HOLD";
        return new StrategyPolicy(strategy, multiplier, disabled, decision, reason.toString().trim());
    }

    private static double replayReplayScore(ReplayStats replay) {
        if (replay == null || replay.samples <= 0) {
            return 0.50;
        }
        double quality = clamp(replay.avgQuality() / 10.0, 0.0, 1.0);
        double ev = clamp(replay.avgExpectedValue() / 8.0, 0.0, 1.0);
        double p = clamp(replay.avgTargetProbability(), 0.0, 1.0);
        return clamp(quality * 0.35 + ev * 0.45 + p * 0.20, 0.0, 1.0);
    }

    private static boolean allowDisable(String strategy) {
        String normalized = normalizeStrategy(strategy);
        Set<String> protectedStrategies = new HashSet<>();
        for (String raw : env("REPLAY_STRATEGY_PROTECTED_DISABLE_LIST", "MARKET_INTELLIGENCE_AI").split(",")) {
            if (raw != null && !raw.isBlank()) {
                protectedStrategies.add(normalizeStrategy(raw));
            }
        }
        return !protectedStrategies.contains(normalized);
    }

    private Map<String, OutcomeStats> readOutcomes() {
        Map<String, OutcomeStats> stats = new HashMap<>();
        if (!Files.exists(outcomesPath)) {
            return stats;
        }
        try (BufferedReader reader = Files.newBufferedReader(outcomesPath, StandardCharsets.UTF_8)) {
            String header = reader.readLine();
            if (header == null) {
                return stats;
            }
            CsvHeader h = new CsvHeader(header);
            String line;
            while ((line = reader.readLine()) != null) {
                List<String> cols = parseCsv(line);
                String eventType = h.get(cols, "eventType");
                String strategy = normalizeStrategy(h.get(cols, "strategyName"));
                String syncedFromBroker = h.get(cols, "syncedFromBroker");
                if (!TradeOutcomeTrainingFilter.isTrainingEligible(eventType, strategy, syncedFromBroker)) {
                    continue;
                }
                double pnl = parseDouble(h.get(cols, "realizedPnlDollars"), 0.0);
                OutcomeStats s = stats.computeIfAbsent(strategy, OutcomeStats::new);
                s.record(pnl);
            }
        } catch (IOException e) {
            System.out.println("REPLAY STRATEGY OUTCOME READ FAILED: " + e.getMessage());
        }
        return stats;
    }

    private Map<String, ReplayStats> readReplay() {
        Map<String, ReplayStats> stats = new HashMap<>();
        if (!Files.exists(replayPath)) {
            return stats;
        }
        try (BufferedReader reader = Files.newBufferedReader(replayPath, StandardCharsets.UTF_8)) {
            String header = reader.readLine();
            if (header == null) {
                return stats;
            }
            CsvHeader h = new CsvHeader(header);
            String line;
            while ((line = reader.readLine()) != null) {
                List<String> cols = parseCsv(line);
                String strategy = normalizeStrategy(h.get(cols, "strategy"));
                if (strategy.isBlank() || "UNKNOWN".equals(strategy)) {
                    continue;
                }
                ReplayStats s = stats.computeIfAbsent(strategy, ReplayStats::new);
                s.record(
                        parseDouble(h.get(cols, "quality"), 0.0),
                        parseDouble(h.get(cols, "expectedValue"), 0.0),
                        parseDouble(h.get(cols, "pTarget"), 0.0),
                        parseDouble(h.get(cols, "proposalScore"), 0.0)
                );
            }
        } catch (IOException e) {
            System.out.println("REPLAY STRATEGY REPORT READ FAILED: " + e.getMessage());
        }
        return stats;
    }

    private void writePolicy(Properties policy) {
        try {
            Path parent = policyPath.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            try (java.io.OutputStream out = Files.newOutputStream(policyPath)) {
                policy.store(out, "Replay-driven strategy policy");
            }
        } catch (IOException e) {
            System.out.println("REPLAY STRATEGY POLICY WRITE FAILED: " + e.getMessage());
        }
    }

    private void writeReport(List<StrategyPolicy> recommendations,
                             Map<String, OutcomeStats> outcomes,
                             Map<String, ReplayStats> replay) {
        try {
            Path parent = reportPath.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            DecimalFormat df = new DecimalFormat("0.0000");
            recommendations.sort((a, b) -> Double.compare(a.multiplier, b.multiplier));
            StringBuilder b = new StringBuilder();
            b.append("REPLAY DRIVEN STRATEGY REPORT\n");
            b.append("generatedAt=").append(Instant.now()).append('\n');
            b.append("outcomeStrategies=").append(outcomes.size()).append('\n');
            b.append("replayStrategies=").append(replay.size()).append('\n');
            b.append("policyPath=").append(policyPath).append('\n');
            b.append('\n');
            for (StrategyPolicy p : recommendations) {
                OutcomeStats o = outcomes.get(p.strategy);
                ReplayStats r = replay.get(p.strategy);
                b.append(p.strategy)
                        .append(" decision=").append(p.decision)
                        .append(" multiplier=").append(df.format(p.multiplier))
                        .append(" outcomes=").append(o == null ? 0 : o.closed)
                        .append(" pnl=").append(df.format(o == null ? 0.0 : o.totalPnl))
                        .append(" expectancy=").append(df.format(o == null ? 0.0 : o.expectancy()))
                        .append(" pf=").append(df.format(o == null ? 0.0 : o.profitFactor()))
                        .append(" replaySamples=").append(r == null ? 0 : r.samples)
                        .append(" replayEv=").append(df.format(r == null ? 0.0 : r.avgExpectedValue()))
                        .append(" reason=").append(p.reason)
                        .append('\n');
            }
            Files.writeString(reportPath, b.toString(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            System.out.println("REPLAY STRATEGY REPORT WRITE FAILED: " + e.getMessage());
        }
    }

    private static String normalizeStrategy(String raw) {
        return TradeOutcomeTrainingFilter.normalizeStrategy(raw);
    }

    private static List<String> parseCsv(String line) {
        List<String> out = new ArrayList<>();
        if (line == null) {
            return out;
        }
        StringBuilder cur = new StringBuilder();
        boolean quoted = false;
        for (int i = 0; i < line.length(); i++) {
            char c = line.charAt(i);
            if (quoted) {
                if (c == '"') {
                    if (i + 1 < line.length() && line.charAt(i + 1) == '"') {
                        cur.append('"');
                        i++;
                    } else {
                        quoted = false;
                    }
                } else {
                    cur.append(c);
                }
            } else if (c == ',') {
                out.add(cur.toString());
                cur.setLength(0);
            } else if (c == '"') {
                quoted = true;
            } else {
                cur.append(c);
            }
        }
        out.add(cur.toString());
        return out;
    }

    private static double parseDouble(String value, double fallback) {
        try {
            return value == null || value.isBlank() ? fallback : Double.parseDouble(value.trim());
        } catch (Exception e) {
            return fallback;
        }
    }

    private static double clamp(double value, double min, double max) {
        if (!Double.isFinite(value)) {
            return min;
        }
        return Math.max(min, Math.min(max, value));
    }

    private static String fmt(double value) {
        if (!Double.isFinite(value)) {
            value = 0.0;
        }
        return String.format(Locale.ROOT, "%.6f", value);
    }

    private static String env(String key, String fallback) {
        String value = System.getenv(key);
        return value == null || value.isBlank() ? fallback : value.trim();
    }

    private static int envInt(String key, int fallback) {
        try {
            String value = System.getenv(key);
            return value == null || value.isBlank() ? fallback : Integer.parseInt(value.trim());
        } catch (Exception e) {
            return fallback;
        }
    }

    private static double envDouble(String key, double fallback) {
        try {
            String value = System.getenv(key);
            return value == null || value.isBlank() ? fallback : Double.parseDouble(value.trim());
        } catch (Exception e) {
            return fallback;
        }
    }

    private static final class CsvHeader {
        private final Map<String, Integer> indexes = new HashMap<>();

        CsvHeader(String header) {
            List<String> cols = parseCsv(header);
            for (int i = 0; i < cols.size(); i++) {
                indexes.put(cols.get(i).trim(), i);
            }
        }

        String get(List<String> cols, String name) {
            Integer idx = indexes.get(name);
            if (idx == null || idx < 0 || idx >= cols.size()) {
                return "";
            }
            return cols.get(idx);
        }
    }

    private static final class OutcomeStats {
        final String strategy;
        int closed;
        int wins;
        int losses;
        int lossStreak;
        double totalPnl;
        double grossProfit;
        double grossLoss;

        OutcomeStats(String strategy) {
            this.strategy = strategy;
        }

        void record(double pnl) {
            closed++;
            totalPnl += pnl;
            if (pnl > 0.0) {
                wins++;
                grossProfit += pnl;
                lossStreak = 0;
            } else if (pnl < 0.0) {
                losses++;
                grossLoss += Math.abs(pnl);
                lossStreak++;
            }
        }

        double winRate() {
            return closed <= 0 ? 0.0 : (double) wins / closed;
        }

        double expectancy() {
            return closed <= 0 ? 0.0 : totalPnl / closed;
        }

        double profitFactor() {
            if (grossLoss <= 0.0) {
                return grossProfit > 0.0 ? 99.0 : 0.0;
            }
            return grossProfit / grossLoss;
        }
    }

    private static final class ReplayStats {
        final String strategy;
        int samples;
        double totalQuality;
        double totalExpectedValue;
        double totalTargetProbability;
        double totalProposalScore;

        ReplayStats(String strategy) {
            this.strategy = strategy;
        }

        void record(double quality, double expectedValue, double targetProbability, double proposalScore) {
            samples++;
            totalQuality += quality;
            totalExpectedValue += expectedValue;
            totalTargetProbability += targetProbability;
            totalProposalScore += proposalScore;
        }

        double avgQuality() {
            return samples <= 0 ? 0.0 : totalQuality / samples;
        }

        double avgExpectedValue() {
            return samples <= 0 ? 0.0 : totalExpectedValue / samples;
        }

        double avgTargetProbability() {
            return samples <= 0 ? 0.0 : totalTargetProbability / samples;
        }
    }

    private static final class StrategyPolicy {
        final String strategy;
        final double multiplier;
        final boolean disabled;
        final String decision;
        final String reason;

        StrategyPolicy(String strategy, double multiplier, boolean disabled, String decision, String reason) {
            this.strategy = strategy;
            this.multiplier = multiplier;
            this.disabled = disabled;
            this.decision = decision;
            this.reason = reason == null ? "" : reason;
        }
    }

    public static final class Result {
        public final int outcomeStrategies;
        public final int replayStrategies;
        public final int recommendations;
        public final Path policyPath;

        Result(int outcomeStrategies, int replayStrategies, int recommendations, Path policyPath) {
            this.outcomeStrategies = outcomeStrategies;
            this.replayStrategies = replayStrategies;
            this.recommendations = recommendations;
            this.policyPath = policyPath;
        }
    }
}
